### PR TITLE
Referencing System.Drawing

### PR DESCRIPTION
**Pull request by microdee**
Little fix which fixes the compiler complaining about missing System.Drawing reference. Now messages can be compiled automatically.

### CODE REVIEW

**Comment by velcrome** [comment]
will look into it. need to research, why this is an issue for you at all.

do you use vs2015 community?

**Comment by microdee** [comment]
solution was for 2013 i opened it with that, i will try 2015 tomorrow then

**Comment by microdee** [comment]
it is working with 2015 flawless. sorry for false alarm :S

**Comment by velcrome** [comment]
Kept this open to investigate, my findings:

The current code references **System.Drawing** twice.

1. **Color** to paint a winform **FormularLayoutPanel**
2. **Point** to detect mouse hits in a winform **FieldPanel**

**Pull request closed without merging**
